version: '3.3'

services:
   sds_frontend:
     image: colav/sds-ui:latest
     container_name: sds_frontend
     depends_on:
       - sds_backend
     ports:
       - "3000:80"
     restart: always
#     mem_reservation: 1024M
#     cpuset: "0-2"
     environment:
       #REACT_APP_API_URL: sds_backend
       SDS_PROXY_BACKEND_HOST: sds_frontend
       SDS_PROXY_BACKEND_PORT: 80
       PORT: 443
       HTTPS: "true"
#       REACT_APP_API_URL: "http://192.168.176.3:8080"
     deploy:
            resources:
                limits:
                  cpus: '2.0'
                  memory: 8192M
     links:
       - sds_backend       

   sds_backend:
     image: colav/sds-backend:latest
     container_name: sds_backend
     depends_on:
       - sds_mongodb
     ports:
       - "8080:8080"
     restart: always
#     mem_reservation: 1024M
#     cpuset: "0-2"
     environment:
       MONGODB_IP: sds_mongodb
     deploy:
            resources:
                limits:
                  cpus: '2.0'
                  memory: 8192M
     links:
       - sds_mongodb
    
   sds_mongodb:
     image: colav/sds-mongodb:latest
     container_name: sds_mongodb
     ports:
       - "27017:27017"
     restart: always
 #    mem_reservation: 2048M
 #    cpuset: "0-2"
     deploy:
            resources:
                limits:
                  cpus: '2.0'
                  memory: 8192M
